"""product category game 3nf

Revision ID: 5bd1e3c1ba48
Revises: 0ad2bdc57b29
Create Date: 2022-08-08 18:18:15.536722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd1e3c1ba48'
down_revision = '0ad2bdc57b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('category_game_id', sa.Integer(), nullable=False))
    op.drop_constraint('Product_game_id_fkey', 'Product', type_='foreignkey')
    op.drop_constraint('Product_category_id_fkey', 'Product', type_='foreignkey')
    op.create_foreign_key(None, 'Product', 'CategoryGame', ['category_game_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Product', 'game_id')
    op.drop_column('Product', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Product', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Product', type_='foreignkey')
    op.create_foreign_key('Product_category_id_fkey', 'Product', 'Category', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('Product_game_id_fkey', 'Product', 'Game', ['game_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Product', 'category_game_id')
    # ### end Alembic commands ###
